// Initial seed data for JK Lights Gandhinagar Showroom
// Ingested & Synchronized from GJAKS & BELUGA Official Catalogs (2025-2026)

export const DEFAULT_STORE_INFO = {
  name: "JK Lights",
  tagline: "Experience The Symphony of Luxury Illumination",
  city: "Gandhinagar, Gujarat",
  address: "2nd Floor, VTC Complex (Vrundavan Trade Center), Above Kabir World, Reliance Cross Road, Kudasan, Gandhinagar - 382421",
  landmark: "Above Kabir World, Opp. Kanam Farm",
  phone: "+91 98980 91234",
  whatsapp: "919898091234",
  email: "contact@jklights.com",
  timingsWeekdays: "Mon - Sat: 10:00 AM - 9:30 PM",
  timingsSunday: "Sunday: 11:00 AM - 8:00 PM",
  gmapsQuery: "https://maps.google.com/?q=J+K+Lights+Gandhinagar+Kudasan",
  gmbSearchUrl: "https://www.google.com/search?q=J+K+Lights+Gandhinagar",
  showroomImage: "assets/showroom.jpg",
  announcementText: "🚚 Free Site Consultation in Gandhinagar & Ahmedabad | 🛠️ Professional Installation | 🛡️ 1 Year Warranty | 🏬 Visit Our Kudasan Showroom"
};

export const DEFAULT_CATEGORIES = [
  { id: "all", name: "All Products", icon: "assets/products/chandelier-imperial-crown.jpg", count: "70+ Models", desc: "Complete luxury lighting collection crafted for bungalows, villas & duplexes." },
  { id: "chandeliers", name: "Grand Chandeliers", icon: "assets/products/chandelier-imperial-crown.jpg", count: "16 Models", desc: "Faceted K9 crystal, imperial crowns, ring halos & amber fluted glass clusters." },
  { id: "double-height", name: "Double Height Chandeliers", icon: "assets/products/double-height-spiral.jpg", count: "11 Models", desc: "3m to 6.85m vertical cascading spirals & raindrop helixes for stairwells & duplexes." },
  { id: "wall", name: "Designer Wall Lights", icon: "assets/products/wall-marble.jpg", count: "14 Models", desc: "Dual-beam architectural up-down sconces, Spanish marble discs & crystal leaf brackets." },
  { id: "pendant", name: "Hanging Pendants", icon: "assets/products/pendant-dining-bar.jpg", count: "5 Models", desc: "Linear dining clusters, fluted cognac drops, faceted crystal cylinders & Scandinavian domes." },
  { id: "table-floor", name: "Table & Floor Lamps", icon: "assets/products/lamp-arched-marble.jpg", count: "11 Models", desc: "Sculptural arched marble floor lamps, amber discs, natural travertine & classic banker lamps." },
  { id: "ceiling", name: "Ceiling Lights", icon: "assets/products/ceiling-triple-ring.jpg", count: "5 Models", desc: "Concentric triple rings, ultra-slim 3-CCT panels & floral crystal flush ceiling fixtures." },
  { id: "track", name: "48V Magnetic Tracks", icon: "assets/products/track-system.jpg", count: "6 Modules", desc: "Low-voltage architectural recessed rails, darklight grilles, rotatable spots & in-track modules." },
  { id: "outdoor", name: "Outdoor & Landscape", icon: "assets/products/outdoor-bollard.jpg", count: "5 Fixtures", desc: "IP65 pathway bollards, IP67 garden spike uplights, facade beams & solar security sconces." },
  { id: "smart", name: "Smart Tunable Lights", icon: "assets/products/smart-halo.jpg", count: "2 Devices", desc: "WiFi & Bluetooth ambient rings, rotary dimmers & 16M color scene controllers." }
];

export const DEFAULT_ROOMS = [
  { id: "living", name: "Living Room & Duplex", image: "assets/rooms/living.jpg", desc: "Opulent Chandeliers & Ambient Halos" },
  { id: "bedroom", name: "Master Bedroom", image: "assets/rooms/bedroom.jpg", desc: "Warm Cove Sconces & Bedside Drops" },
  { id: "dining", name: "Dining & Bar", image: "assets/rooms/dining.jpg", desc: "Stunning Linear & Cluster Pendants" },
  { id: "kitchen", name: "Kitchen Island", image: "assets/rooms/dining.jpg", desc: "Task Under-Cabinet & Island Pendants" },
  { id: "office", name: "Office & Study", image: "assets/rooms/living.jpg", desc: "Anti-Glare Magnetic Architectural Tracks" },
  { id: "outdoor", name: "Outdoor & Facade", image: "assets/products/outdoor-bollard.jpg", desc: "Waterproof Bollards & Facade Beams" }
];

export const DEFAULT_PRODUCTS = [
  // ================= 1. GRAND CHANDELIERS =================
  {
    id: "prod-SS7640",
    name: "SS7640 Nordic Golden Ring Halo Chandelier",
    category: "chandeliers",
    room: "living",
    price: 6999,
    originalPrice: 9470,
    discount: "26% OFF",
    rating: 4.9,
    reviewsCount: 42,
    image: "assets/products/chandelier-halo.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Showroom Star",
    description: "Triple-tier concentric glowing halos in satin French Gold. Features multi-angle suspension wires for customized angle layouts and remote 3-color tunable brightness.",
    specs: {
      modelCode: "SS7640",
      material: "Aviation Aluminum & Silica Optical Rings",
      dimensions: "D800 + D600 + D400mm Triple Tier",
      wattageCct: "108W 3-CCT Smart Tunable LED",
      finish: "French Satin Gold",
      voltage: "220-240V 50Hz"
    }
  },
  {
    id: "prod-TN9542",
    name: "TN9542 Artisan Frosted Acrylic Halo Chandelier",
    category: "chandeliers",
    room: "dining",
    price: 6499,
    originalPrice: 8640,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 28,
    image: "assets/products/chandelier-halo.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Modernist",
    description: "Sleek circular acrylic floating halo chandelier delivering a soft, non-glare diffused downlight perfect over 6-seater dining setups.",
    specs: {
      modelCode: "TN9542/480MM",
      material: "Die-cast Aluminum & Frosted PMMA Diffuser",
      dimensions: "Diameter 480mm, Drop 1200mm",
      wattageCct: "48W Warm White 3000K",
      finish: "Rose Gold & Textured Black",
      voltage: "220V AC"
    }
  },
  {
    id: "prod-TN5138",
    name: "TN5138 Geometric Nesting Ring Chandelier",
    category: "chandeliers",
    room: "living",
    price: 8990,
    originalPrice: 12480,
    discount: "28% OFF",
    rating: 4.9,
    reviewsCount: 34,
    image: "assets/products/chandelier-halo.jpg",
    featured: true,
    trending: false,
    inStock: true,
    badge: "Architect's Pick",
    description: "Interlocking architectural glowing hoops creating an avant-garde artistic silhouette with uniform 360-degree ambient lighting.",
    specs: {
      modelCode: "TN5138/610MM",
      material: "Brushed Aluminum & Silica Diffuser",
      dimensions: "Diameter 610mm x Height 1500mm",
      wattageCct: "72W High Lumen LED (3000K/4000K/6000K)",
      finish: "Champagne Gold",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-MT2176-L4",
    name: "MT2176-L4 Linear Minimalist Dining Island Chandelier",
    category: "chandeliers",
    room: "dining",
    price: 6490,
    originalPrice: 8820,
    discount: "26% OFF",
    rating: 4.8,
    reviewsCount: 22,
    image: "assets/products/pendant-dining-bar.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Island Bestseller",
    description: "Streamlined horizontal linear bar featuring 4 downward focused anti-glare cones engineered specifically for modern kitchen islands and dining tables.",
    specs: {
      modelCode: "MT2176-L4",
      material: "Extruded Aluminum & Spun Brass Accents",
      dimensions: "L1200 x W200 x H1500mm Adjustable",
      wattageCct: "4-Head Integrated COB 48W",
      finish: "Matte Black & Antique Brass",
      voltage: "220V"
    }
  },
  {
    id: "prod-MT21787-12",
    name: "MT21787-12 Contemporary 12-Light Sputnik Chandelier",
    category: "chandeliers",
    room: "living",
    price: 11990,
    originalPrice: 16090,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 39,
    image: "assets/products/chandelier.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Mid-Century Modern",
    description: "Mid-century 12-arm radial starburst fixture bringing dynamic drama and expansive illumination to high-ceiling drawing rooms.",
    specs: {
      modelCode: "MT21787-12",
      material: "Forged Iron Arms & Brass Sockets",
      dimensions: "D850mm x H650mm + 500mm Rod",
      lampHolder: "12x G9 Bulbs (Compatible with Dimmable LED)",
      finish: "Brushed Brass & Deep Black",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-KD8022",
    name: "KD8022 Tiered K9 Crystal Grand Chandelier",
    category: "chandeliers",
    room: "living",
    price: 9990,
    originalPrice: 13710,
    discount: "27% OFF",
    rating: 5.0,
    reviewsCount: 51,
    image: "assets/products/chandelier.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Luxury Crystal",
    description: "Cascading concentric tiers of precision cut K9 crystal prisms that refract light into vibrant rainbow glimmers across the room.",
    specs: {
      modelCode: "KD8022/600R",
      material: "Faceted K9 Optical Crystal & Polished Gold Frame",
      dimensions: "Diameter 600mm x Height 450mm",
      lampHolder: "9x E14 Lamp Holders",
      finish: "24K Gold PVD Mirror Finish",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-KD2331",
    name: "KD2331 Square Waterfall Faceted Crystal Chandelier",
    category: "chandeliers",
    room: "living",
    price: 16990,
    originalPrice: 23840,
    discount: "29% OFF",
    rating: 4.9,
    reviewsCount: 33,
    image: "assets/products/chandelier.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Royal Palace",
    description: "Geometric square cascade composed of multi-angled crystal prisms designed for neoclassical drawing rooms and master suites.",
    specs: {
      modelCode: "KD2331/600S",
      material: "Precision Cut Triangular Crystal Bars & Brass",
      dimensions: "600 x 600mm Square x H400mm",
      lampHolder: "12x E14 LED Bulbs",
      finish: "High Gloss Gold",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-KDA039",
    name: "KDA039 Rectangular Crystal Prism Dining Chandelier",
    category: "chandeliers",
    room: "dining",
    price: 14990,
    originalPrice: 20260,
    discount: "26% OFF",
    rating: 4.9,
    reviewsCount: 27,
    image: "assets/products/pendant-dining-bar.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Dining Showpiece",
    description: "Elongated luxury crystal prism bar designed to hang gracefully above 8 to 10-seater dining banquet tables.",
    specs: {
      modelCode: "KDA039/800S",
      material: "Fluted K9 Crystal & Heavy Gauge Brass",
      dimensions: "L800 x W350 x H350mm (Drop 1500mm)",
      lampHolder: "16x G9 LED Bulbs",
      finish: "Champagne Brass",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-B1078",
    name: "Beluga B1078 Smoked Glass Sphere Cluster Chandelier",
    category: "chandeliers",
    room: "living",
    price: 11850,
    originalPrice: 15990,
    discount: "26% OFF",
    rating: 4.8,
    reviewsCount: 19,
    image: "assets/products/chandelier-smoked-sphere.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Beluga Exclusive",
    description: "Contemporary cluster of hand-blown smoked cognac glass orbs creating a mood-lit, ultra-luxurious evening atmosphere.",
    specs: {
      modelCode: "BELUGA-B1078",
      material: "Hand-Blown Smoked Glass & Titanium Frame",
      dimensions: "D750mm x H600mm",
      lampHolder: "8x E27 Filament Warm LED",
      finish: "Titanium Chrome & Smoked Cognac",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-B8015",
    name: "Beluga B8015 Amber Fluted Glass Cluster Chandelier",
    category: "chandeliers",
    room: "dining",
    price: 11850,
    originalPrice: 15990,
    discount: "26% OFF",
    rating: 4.9,
    reviewsCount: 24,
    image: "assets/products/chandelier-amber-fluted.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Beluga Series",
    description: "Hand-pleated amber glass shades with brushed gold hardware, evoking European warmth and mid-century elegance.",
    specs: {
      modelCode: "BELUGA-B8015",
      material: "Fluted Amber Glass & Brushed Gold",
      dimensions: "D650mm x H550mm",
      lampHolder: "6x E27 Warm White LED",
      finish: "Brushed French Gold",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-B6611",
    name: "Beluga B6611 Grand Imperial Crystal Crown Chandelier",
    category: "chandeliers",
    room: "living",
    price: 36990,
    originalPrice: 49910,
    discount: "26% OFF",
    rating: 5.0,
    reviewsCount: 44,
    image: "assets/products/chandelier-imperial-crown.jpg",
    featured: true,
    trending: false,
    inStock: true,
    badge: "Royal Jewel",
    description: "Massive crown chandelier featuring hundreds of diamond-faceted crystal spears radiating royal opulence in grand living rooms.",
    specs: {
      modelCode: "BELUGA-B6611/196",
      material: "Diamond Cut K9 Crystal & Electroplated Gold",
      dimensions: "D900mm x H1200mm Drop",
      lampHolder: "18x E14 LED Bulbs",
      finish: "Imperial 24K Gold PVD",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-ER25003",
    name: "ER25003 Elegance Ring Halo Crystal Chandelier",
    category: "chandeliers",
    room: "living",
    price: 24490,
    originalPrice: 32780,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 31,
    image: "assets/products/chandelier-halo.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Trending 2026",
    description: "Continuous circle of crystal baguettes internally illuminated by high CRI LEDs, offering seamless warm-to-cool tunable ambiance.",
    specs: {
      modelCode: "ER25003/800",
      material: "K9 Crystal Inlaid Ring & Satin Brass",
      dimensions: "Diameter 800mm, Cable 1500mm",
      wattageCct: "80W Tunable LED 3000K-6500K",
      finish: "Satin Brushed Gold",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-ER8003",
    name: "ER8003 Spiral Drop Crystal Chandelier",
    category: "chandeliers",
    room: "living",
    price: 20990,
    originalPrice: 28160,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 29,
    image: "assets/products/chandelier.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Showroom Exclusive",
    description: "Dynamic swirling spiral formation of crystal drops providing shimmering multidirectional light distribution.",
    specs: {
      modelCode: "ER8003",
      material: "Cut Crystals & Polished Brass Chassis",
      dimensions: "D600mm x H850mm",
      lampHolder: "12x E14 LED Bulbs",
      finish: "Polished French Brass",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-ER9232",
    name: "ER9232 Heritage Palace 24-Light Grand Chandelier",
    category: "chandeliers",
    room: "living",
    price: 37900,
    originalPrice: 50550,
    discount: "25% OFF",
    rating: 5.0,
    reviewsCount: 41,
    image: "assets/products/chandelier-imperial-crown.jpg",
    featured: true,
    trending: false,
    inStock: true,
    badge: "Heritage Collection",
    description: "Traditional two-tier European palace candelabra silhouette adorned with crystal garlands and bobeches for palatial villas.",
    specs: {
      modelCode: "ER9232",
      material: "Solid Cast Brass & K9 Precision Prisms",
      dimensions: "D1000mm x H1300mm",
      lampHolder: "24x E14 Candle Bulbs",
      finish: "Royal Antique Gold",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-ER9076",
    name: "ER9076 Grand Emperor Double Tier 48-Light Chandelier",
    category: "chandeliers",
    room: "living",
    price: 112000,
    originalPrice: 149000,
    discount: "25% OFF",
    rating: 5.0,
    reviewsCount: 15,
    image: "assets/products/chandelier-imperial-crown.jpg",
    featured: true,
    trending: false,
    inStock: true,
    badge: "Masterpiece",
    description: "Monumental 48-light chandelier engineered for luxury bungalows, farmhouses, and banquet spaces demanding an unforgettable centerpiece.",
    specs: {
      modelCode: "ER9076",
      material: "Forged Brass Core & Bohemian Cut Crystal",
      dimensions: "D1400mm x H2200mm",
      lampHolder: "48x E14 Bulbs",
      finish: "Imperial 24K Gold",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-KDF8100",
    name: "KDF8100 Prestige Art Deco Fluted Glass Rod Chandelier",
    category: "chandeliers",
    room: "living",
    price: 57500,
    originalPrice: 76790,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 23,
    image: "assets/products/chandelier-amber-fluted.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Art Deco",
    description: "Architectural Art Deco cylinder array made of individual textured glass tubes that glow with exquisite golden warmth.",
    specs: {
      modelCode: "KDF8100/600",
      material: "Handcrafted Borosilicate Fluted Tubes & Gold Brass",
      dimensions: "D600mm x H750mm",
      lampHolder: "14x G9 Bulbs",
      finish: "Champagne Polished Brass",
      voltage: "220-240V"
    }
  },

  // ================= 2. DOUBLE HEIGHT STAIRWELL CHANDELIERS =================
  {
    id: "prod-MTD23775",
    name: "MTD23775-7D 388W Grand Duplex Spiral Chandelier",
    category: "double-height",
    room: "living",
    price: 33900,
    originalPrice: 44990,
    discount: "25% OFF",
    rating: 5.0,
    reviewsCount: 48,
    image: "assets/products/double-height-spiral.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "3.5m Staircase Drop",
    description: "Sculptural 7-ring spiral helix chandelier engineered specifically for double-height staircase voids and duplex foyers. Includes remote control.",
    specs: {
      modelCode: "MTD23775-7D",
      material: "Heavy Aluminum Canopy & Silica Light Rings",
      dimensions: "Diameter 800mm x Total Drop 3500mm (3.5m)",
      wattageCct: "388W High Lumen 3-CCT Integrated LED",
      finish: "Satin French Gold",
      voltage: "220-240V AC"
    }
  },
  {
    id: "prod-MT21704-7H",
    name: "MT21704-7H French Gold Cascading Raindrop Stairwell Chandelier",
    category: "double-height",
    room: "living",
    price: 13990,
    originalPrice: 18770,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 32,
    image: "assets/products/double-height.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "3.0m Duplex Drop",
    description: "Delicate cascading raindrop pendants creating a magical vertical light waterfall down high-ceiling stairwells.",
    specs: {
      modelCode: "MT21704-7H/FG",
      material: "Spun Brass Cones & Laser Crystal Pods",
      dimensions: "D600mm x H3000mm (3.0m Drop)",
      wattageCct: "200W Integrated LED (Warm White)",
      finish: "French Satin Gold",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-MT21704-11C",
    name: "MT21704/11C Grand 11-Tier Duplex Staircase Chandelier",
    category: "double-height",
    room: "living",
    price: 32500,
    originalPrice: 42910,
    discount: "24% OFF",
    rating: 5.0,
    reviewsCount: 21,
    image: "assets/products/double-height-spiral.jpg",
    featured: true,
    trending: false,
    inStock: true,
    badge: "6.85m Mega Drop",
    description: "Massive 6.85-meter drop 11-tier staircase chandelier designed for triple-height atriums and palatial entrance halls.",
    specs: {
      modelCode: "MT21704/11C FG",
      material: "Reinforced Brass Chassis & Crystal Pendants",
      dimensions: "D800mm x Total Height 6850mm (6.85m Drop)",
      wattageCct: "438W High Power LED Array",
      finish: "French Gold",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-T0159",
    name: "T0159/37B 37-Globe Stairwell Meteor Shower Chandelier",
    category: "double-height",
    room: "living",
    price: 46800,
    originalPrice: 62520,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 29,
    image: "assets/products/chandelier-smoked-sphere.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "5.0m Meteor Drop",
    description: "37 illuminated bubble glass globes suspended at staggered heights mimicking a cosmic meteor shower across duplex ceilings.",
    specs: {
      modelCode: "T0159/37B",
      material: "Hand-Blown Champagne Bubble Glass Orbs & Brass",
      dimensions: "Canopy D900mm x Height 5000mm (5m Drop)",
      lampHolder: "37x G4 LED Bulbs",
      finish: "Champagne Gold & Clear Bubble Glass",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-B5127",
    name: "Beluga B5127/25 25-Pendant Double Height Spiral Chandelier",
    category: "double-height",
    room: "living",
    price: 29990,
    originalPrice: 40230,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 37,
    image: "assets/products/double-height-spiral.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "4.0m Spiral Drop",
    description: "Beluga collection 25-light spiral staircase cascade with faceted crystal pods casting brilliant starry reflections.",
    specs: {
      modelCode: "BELUGA-B5127/25 FG",
      material: "K9 Champagne Crystal Pods & Gold Base",
      dimensions: "D800mm x Height 4000mm (4m Drop)",
      lampHolder: "25x G9 LED Bulbs",
      finish: "French Gold & Champagne Crystal",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-DT8989",
    name: "DT8989/18 Architectural Iron & Natural Marble Duplex Chandelier",
    category: "double-height",
    room: "living",
    price: 48200,
    originalPrice: 64380,
    discount: "25% OFF",
    rating: 5.0,
    reviewsCount: 18,
    image: "assets/products/wall-marble.jpg",
    featured: true,
    trending: false,
    inStock: true,
    badge: "Natural Marble & Iron",
    description: "Unique fusion of raw Spanish natural marble discs and matte black architectural iron arms for luxury organic-modern homes.",
    specs: {
      modelCode: "DT8989/18",
      material: "Spanish Natural White Marble & Forged Black Iron",
      dimensions: "D850mm x Drop 4200mm (4.2m)",
      wattageCct: "18-Light Integrated Warm LED 216W",
      finish: "Matte Black & Natural Veined Marble",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-DT8988",
    name: "DT8988 Prismatic 288W Stairwell Pendant Centerpiece",
    category: "double-height",
    room: "living",
    price: 48200,
    originalPrice: 64380,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 26,
    image: "assets/products/double-height.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "288W High Lumen",
    description: "High-output 288W luminous crystal-textured pillars descending in an organic spiral formation.",
    specs: {
      modelCode: "DT8988",
      material: "Extruded Prismatic Acrylic & Gold Alloy",
      dimensions: "D750mm x H3800mm (3.8m Drop)",
      wattageCct: "288W 3-CCT Smart LED",
      finish: "Matte Champagne Gold",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-DT2132",
    name: "DT2132/18 18-Drop Crystal Cylinder Staircase Chandelier",
    category: "double-height",
    room: "living",
    price: 45500,
    originalPrice: 60740,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 25,
    image: "assets/products/double-height-spiral.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "3.6m Duplex Drop",
    description: "Heavy solid crystal fluted rods delivering crystal clarity and dramatic vertical illumination for staircases.",
    specs: {
      modelCode: "DT2132/18",
      material: "Solid Fluted Crystal Cylinders & Brushed Brass",
      dimensions: "D700mm x Drop 3600mm (3.6m)",
      lampHolder: "18x G9 LED",
      finish: "Brushed Brass",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-ER9216",
    name: "ER9216 32-Light Imperial Grand Ballroom Double Height Chandelier",
    category: "double-height",
    room: "living",
    price: 112000,
    originalPrice: 149000,
    discount: "25% OFF",
    rating: 5.0,
    reviewsCount: 14,
    image: "assets/products/chandelier-imperial-crown.jpg",
    featured: true,
    trending: false,
    inStock: true,
    badge: "Grand Ballroom",
    description: "Magnificent two-tier grand chandelier designed for double-height banquet halls and palatial living spaces.",
    specs: {
      modelCode: "ER9216",
      material: "Cast Brass & Bohemian Faceted Crystals",
      dimensions: "Diameter 1200mm x Drop 2150mm",
      lampHolder: "32x E14 LED Bulbs",
      finish: "24K Gold PVD Finish",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-MH2918",
    name: "MH2918/1800 44-Light Starburst Galaxy Duplex Chandelier",
    category: "double-height",
    room: "living",
    price: 69900,
    originalPrice: 92380,
    discount: "24% OFF",
    rating: 5.0,
    reviewsCount: 20,
    image: "assets/products/double-height-spiral.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "44-Light Galaxy",
    description: "44 crystal-tipped radiant beams arranged in a cascading galaxy spiral down the staircase atrium.",
    specs: {
      modelCode: "MH2918/1800",
      material: "Plated Brass Rods & Crystal Star Points",
      dimensions: "D1000mm x Drop 4500mm (4.5m)",
      lampHolder: "44x G4 LED Bulbs",
      finish: "24K Gold Plated",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-MH2932",
    name: "MH2932/1800 43-Light Crystal Helix Duplex Staircase Chandelier",
    category: "double-height",
    room: "living",
    price: 64800,
    originalPrice: 86420,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 17,
    image: "assets/products/double-height-spiral.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "43-Light Helix",
    description: "Staggered 43-drop crystal helix that captures daylight and emits brilliant warm evening light.",
    specs: {
      modelCode: "MH2932/1800",
      material: "Champagne Crystal Drops & Mirror Gold Plate",
      dimensions: "D1000mm x Drop 4800mm (4.8m)",
      lampHolder: "43x G4 LED Bulbs",
      finish: "Mirror Gold & Champagne Glass",
      voltage: "220-240V"
    }
  },

  // ================= 3. DESIGNER WALL SCONCES & MIRROR LIGHTS =================
  {
    id: "prod-SS1973",
    name: "SS1973 Contemporary Minimalist Up-Down Wall Sconce",
    category: "wall",
    room: "living",
    price: 1750,
    originalPrice: 2380,
    discount: "26% OFF",
    rating: 4.9,
    reviewsCount: 64,
    image: "assets/products/wall-up-down.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Architect's Choice",
    description: "Dual upward and downward optical lenses projecting razor-sharp warm light cones on textured wallpaper and accent walls.",
    specs: {
      modelCode: "SS1973",
      material: "Die-cast Aluminum Body",
      dimensions: "W100 x D80 x H280mm",
      wattageCct: "12W CREE Warm White 3000K",
      finish: "Matte Black & Gold Accent",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-SS2738",
    name: "SS2738 Curved Ambient Halo Wall Light",
    category: "wall",
    room: "bedroom",
    price: 1950,
    originalPrice: 2600,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 38,
    image: "assets/products/wall.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Bedside Sconce",
    description: "Graceful sweeping curved silhouette offering indirect cove-style wall wash illumination ideal for luxury bedrooms.",
    specs: {
      modelCode: "SS2738",
      material: "Curved Aluminum & PMMA Diffuser",
      dimensions: "W120 x H320mm",
      wattageCct: "14W 3-Color CCT LED",
      finish: "Brushed Brass",
      voltage: "220V"
    }
  },
  {
    id: "prod-SS2967",
    name: "SS2967 Natural Spanish Marble & Brass Wall Sconce",
    category: "wall",
    room: "living",
    price: 2790,
    originalPrice: 3750,
    discount: "26% OFF",
    rating: 5.0,
    reviewsCount: 49,
    image: "assets/products/wall-marble.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Real Marble",
    description: "Natural veined marble backplate with an illuminated front brass disc, creating back-lit halo ambient glow.",
    specs: {
      modelCode: "SS2967",
      material: "Authentic Natural Marble & Solid Brass",
      dimensions: "W150 x H380mm",
      lampHolder: "1x G9 LED 7W",
      finish: "Spanish White Marble & Satin Gold",
      voltage: "220V"
    }
  },
  {
    id: "prod-SS3158",
    name: "SS3158 Geometric Ribbon LED Accent Wall Light",
    category: "wall",
    room: "bedroom",
    price: 2280,
    originalPrice: 3040,
    discount: "25% OFF",
    rating: 4.7,
    reviewsCount: 31,
    image: "assets/products/wall.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Minimalist Art",
    description: "Sculptural ribbon motif casting continuous fluid light along bedroom corridors and foyer walls.",
    specs: {
      modelCode: "SS3158",
      material: "Spun Aluminum Ribbon & Silicone Diffuser",
      dimensions: "W180 x H420mm",
      wattageCct: "18W Tunable LED",
      finish: "Matte Gold",
      voltage: "220V"
    }
  },
  {
    id: "prod-SS2799",
    name: "SS2799-80 Linear Vanity & Bathroom Mirror Sconce",
    category: "wall",
    room: "bedroom",
    price: 2690,
    originalPrice: 3590,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 45,
    image: "assets/products/wall-up-down.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Vanity Waterproof",
    description: "Wide, shadow-free linear bathroom mirror light with moisture resistance and high color-rendering index.",
    specs: {
      modelCode: "SS2799-80",
      material: "Anodized Aluminum & Acrylic Diffuser",
      dimensions: "Length 800mm x H60mm",
      wattageCct: "20W High CRI RA>92 LED (IP54)",
      finish: "Brushed Rose Gold",
      voltage: "220V"
    }
  },
  {
    id: "prod-SS1969",
    name: "SS1969-3 3-Light Frosted Globe Vanity Wall Fixture",
    category: "wall",
    room: "bedroom",
    price: 4190,
    originalPrice: 5630,
    discount: "26% OFF",
    rating: 4.9,
    reviewsCount: 27,
    image: "assets/products/wall.jpg",
    featured: false,
    trending: false,
    inStock: true,
    badge: "Opal Globe",
    description: "Three opal glass spheres mounted on a satin brass horizontal stem providing warm, glare-free illumination.",
    specs: {
      modelCode: "SS1969-3",
      material: "Opal White Frosted Glass & Polished Brass",
      dimensions: "L550 x H200mm",
      lampHolder: "3x G9 LED",
      finish: "Brushed Brass",
      voltage: "220V"
    }
  },
  {
    id: "prod-SS3299B",
    name: "SS3299B Artisan Rosewood & Polished Marble Sconce",
    category: "wall",
    room: "living",
    price: 3600,
    originalPrice: 4800,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 22,
    image: "assets/products/wall-marble.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Wood & Marble",
    description: "Exquisite pairing of rich wood grain, natural stone, and warm filament glow for luxury rustic and contemporary interiors.",
    specs: {
      modelCode: "SS3299B",
      material: "Real Teakwood Finish, Polished Marble & Brass",
      dimensions: "W160 x H350mm",
      lampHolder: "1x E27 Filament",
      finish: "Warm Teak & Marble",
      voltage: "220V"
    }
  },
  {
    id: "prod-SS3313A",
    name: "SS3313A Sculptural Crystal Leaf Luxury Wall Light",
    category: "wall",
    room: "living",
    price: 4200,
    originalPrice: 5630,
    discount: "25% OFF",
    rating: 5.0,
    reviewsCount: 36,
    image: "assets/products/wall.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Crystal Leaf",
    description: "Hand-molded crystal glass leaves radiating from a gold stem that sparkles with diamond brilliance.",
    specs: {
      modelCode: "SS3313A",
      material: "Hand-Molded Crystal Leaves & Gold Chassis",
      dimensions: "W220 x H450mm",
      lampHolder: "2x E14 LED",
      finish: "French Gold",
      voltage: "220V"
    }
  },
  {
    id: "prod-DKMB5277",
    name: "DKMB5277-2 Double Cone Vintage Brass Wall Light",
    category: "wall",
    room: "living",
    price: 5350,
    originalPrice: 7150,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 19,
    image: "assets/products/wall-up-down.jpg",
    featured: false,
    trending: false,
    inStock: true,
    badge: "Vintage Brass",
    description: "Mid-century Italian double-conical sconce offering directional up-down illumination.",
    specs: {
      modelCode: "DKMB5277-2",
      material: "Heavy Spun Brass & Matte Black Metal",
      dimensions: "W320 x H240mm",
      lampHolder: "2x E27 Lamps",
      finish: "Brushed Brass & Black",
      voltage: "220V"
    }
  },
  {
    id: "prod-LM9002",
    name: "LM9002/1 Fluted Amber Glass Designer Sconce",
    category: "wall",
    room: "dining",
    price: 2550,
    originalPrice: 3420,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 33,
    image: "assets/products/chandelier-amber-fluted.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Amber Glass",
    description: "Amber ribbed cylindrical glass shade diffusing honey-warm illumination for dining alcoves.",
    specs: {
      modelCode: "LM9002/1",
      material: "Textured Fluted Amber Glass & Brass Arm",
      dimensions: "W140 x H300mm",
      lampHolder: "1x E27 Warm LED",
      finish: "Amber & Antique Gold",
      voltage: "220V"
    }
  },
  {
    id: "prod-B6616",
    name: "Beluga B6616/2 Handcrafted Ceramic & Brass Wall Light",
    category: "wall",
    room: "living",
    price: 5750,
    originalPrice: 7680,
    discount: "25% OFF",
    rating: 5.0,
    reviewsCount: 21,
    image: "assets/products/wall-marble.jpg",
    featured: true,
    trending: false,
    inStock: true,
    badge: "Artisan Ceramic",
    description: "Artisan ceramic fluting layered with warm gold metalwork for high-end boutique interiors.",
    specs: {
      modelCode: "BELUGA-B6616/2",
      material: "Matte White Ceramic & Electroplated Brass",
      dimensions: "W200 x H360mm",
      lampHolder: "2x G9 LED",
      finish: "Pure White Ceramic & Gold",
      voltage: "220V"
    }
  },
  {
    id: "prod-WDB1674",
    name: "Beluga WDB1674/5 5-Tier Crystal Waterfall Wall Sconce",
    category: "wall",
    room: "living",
    price: 4890,
    originalPrice: 6560,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 41,
    image: "assets/products/wall.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Waterfall Sconce",
    description: "Five cascading tiers of crystal prisms creating a dramatic waterfall of sparkling light.",
    specs: {
      modelCode: "WDB1674/5",
      material: "5-Tier K9 Faceted Crystal & Gold Plating",
      dimensions: "W300 x H520mm",
      lampHolder: "5x E14 Bulbs",
      finish: "24K Gold PVD",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-WDB1225",
    name: "WDB1225 Artistic Songbird on Branch Ambient Wall Light",
    category: "wall",
    room: "bedroom",
    price: 2590,
    originalPrice: 3480,
    discount: "26% OFF",
    rating: 4.9,
    reviewsCount: 53,
    image: "assets/products/wall.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Songbird Series",
    description: "Enchanting illuminated bird perched on a brass twig, offering gentle bedtime ambient lighting.",
    specs: {
      modelCode: "WDB1225",
      material: "Illuminated Frosted Acrylic Bird & Gold Brass Branch",
      dimensions: "W280 x H360mm",
      wattageCct: "12W 3000K Soft Glow LED",
      finish: "Gold & Translucent White",
      voltage: "220V"
    }
  },
  {
    id: "prod-WDB1172",
    name: "WDB1172 Contemporary Triangular Crystal Rod Wall Sconce",
    category: "wall",
    room: "living",
    price: 3100,
    originalPrice: 4140,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 28,
    image: "assets/products/wall.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Crystal Rods",
    description: "Vertical array of triangular crystal rods framing warm internal candle bulbs.",
    specs: {
      modelCode: "WDB1172",
      material: "Prismatic Triangular Crystal Rods & Satin Gold",
      dimensions: "W180 x H400mm",
      lampHolder: "2x E14 LED",
      finish: "Satin Gold",
      voltage: "220V"
    }
  },

  // ================= 4. HANGING PENDANT LIGHTS =================
  {
    id: "prod-BEL-HP101",
    name: "Beluga BEL-HP101 Fluted Cognac Glass Drop Pendant",
    category: "pendant",
    room: "dining",
    price: 3290,
    originalPrice: 4450,
    discount: "26% OFF",
    rating: 4.9,
    reviewsCount: 36,
    image: "assets/products/pendant.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Fluted Cognac",
    description: "Rich cognac fluted glass pendant providing warm ambient dining glow.",
    specs: {
      modelCode: "BEL-HP101",
      material: "Hand-Blown Ribbed Cognac Glass & Brass Cap",
      dimensions: "D180 x H380mm (Cord 1500mm)",
      lampHolder: "1x E27 Filament LED",
      finish: "Cognac Amber & Brushed Gold",
      voltage: "220V"
    }
  },
  {
    id: "prod-BEL-HP205",
    name: "Beluga BEL-HP205 Triple Cluster Linear Dining Bar Pendant",
    category: "pendant",
    room: "dining",
    price: 8890,
    originalPrice: 11900,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 30,
    image: "assets/products/pendant-dining-bar.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Dining Trio",
    description: "Three staggered smoked glass shades mounted on a matte black ceiling canopy for rectangular dining tables.",
    specs: {
      modelCode: "BEL-HP205",
      material: "Smoked Mirror Glass & Matte Black Bar",
      dimensions: "Linear Bar L900mm x Drop 1200mm",
      lampHolder: "3x E27 LED",
      finish: "Smoked Grey Mirror & Black",
      voltage: "220V"
    }
  },
  {
    id: "prod-BEL-HP312",
    name: "Beluga BEL-HP312 Golden Globe Ring Suspension Pendant",
    category: "pendant",
    room: "bedroom",
    price: 4990,
    originalPrice: 6750,
    discount: "26% OFF",
    rating: 4.8,
    reviewsCount: 22,
    image: "assets/products/chandelier-halo.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Golden Ring",
    description: "Luminous frosted glass sphere nestled inside a slender gold ring, perfect for bedside suspension.",
    specs: {
      modelCode: "BEL-HP312",
      material: "Satin Gold Brass Ring & Opal Glass Sphere",
      dimensions: "Diameter 350mm Ring (Cord 1200mm)",
      wattageCct: "20W Tunable LED",
      finish: "Satin Gold & Opal White",
      voltage: "220V"
    }
  },
  {
    id: "prod-BEL-HP420",
    name: "Beluga BEL-HP420 Faceted Crystal Cylinder Island Pendant",
    category: "pendant",
    room: "kitchen",
    price: 4290,
    originalPrice: 5800,
    discount: "26% OFF",
    rating: 5.0,
    reviewsCount: 40,
    image: "assets/products/pendant.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Island Crystal",
    description: "Solid crystal cylinder focusing a warm sparkle onto breakfast counters and bar islands.",
    specs: {
      modelCode: "BEL-HP420",
      material: "Solid Faceted Optical Crystal & Brushed Brass",
      dimensions: "D100 x H450mm",
      wattageCct: "12W High CRI COB 3000K",
      finish: "French Gold & Clear Crystal",
      voltage: "220V"
    }
  },
  {
    id: "prod-SS-P1021",
    name: "SS-P1021 Nordic Scandinavian Wood & Pastel Dome Pendant",
    category: "pendant",
    room: "dining",
    price: 2390,
    originalPrice: 3200,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 28,
    image: "assets/products/pendant-dining-bar.jpg",
    featured: false,
    trending: false,
    inStock: true,
    badge: "Nordic Wood",
    description: "Scandinavian minimalism featuring smooth matte pastel aluminum crowned with natural solid wood.",
    specs: {
      modelCode: "SS-P1021",
      material: "Spun Aluminum & Natural Ash Wood Top",
      dimensions: "D300 x H200mm",
      lampHolder: "1x E27",
      finish: "Matte Grey & Ash Wood",
      voltage: "220V"
    }
  },

  // ================= 5. LUXURY TABLE & FLOOR LAMPS =================
  {
    id: "prod-KK9279A",
    name: "KK9279A Modernist Brushed Brass Arc Table Lamp",
    category: "table-floor",
    room: "bedroom",
    price: 5490,
    originalPrice: 7360,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 31,
    image: "assets/products/table-floor.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Desk Elegance",
    description: "Sculptural arched table lamp crafted from solid brushed brass, delivering warm task and ambient bedside glow.",
    specs: {
      modelCode: "KK9279A",
      material: "Brushed Brass Metal & Heavy Weighted Base",
      dimensions: "W250 x H480mm",
      lampHolder: "1x E27 LED Warm Bulb",
      finish: "Brushed Gold",
      voltage: "220V"
    }
  },
  {
    id: "prod-KK9367A",
    name: "KK9367A Contemporary Smoked Glass Globe Table Lamp",
    category: "table-floor",
    room: "living",
    price: 7990,
    originalPrice: 10880,
    discount: "27% OFF",
    rating: 4.9,
    reviewsCount: 24,
    image: "assets/products/chandelier-smoked-sphere.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Smoked Globe",
    description: "Translucent smoked glass sphere sitting on a minimalist gold pedestal, casting an intimate moody ambiance.",
    specs: {
      modelCode: "KK9367A",
      material: "Hand-Blown Smoked Glass & Gold Metal Pedestal",
      dimensions: "Diameter 280mm x Height 420mm",
      lampHolder: "1x E27 Vintage Filament",
      finish: "Smoked Grey Glass & Gold",
      voltage: "220V"
    }
  },
  {
    id: "prod-KK8006A",
    name: "KK8006A Minimalist Textured Ceramic Bedside Lamp",
    category: "table-floor",
    room: "bedroom",
    price: 6450,
    originalPrice: 8640,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 29,
    image: "assets/products/table-floor.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Ceramic & Linen",
    description: "Tactile ribbed ceramic base paired with an organic linen drum shade for soothing bedroom lighting.",
    specs: {
      modelCode: "KK8006A",
      material: "Handcrafted Textured Ceramic & Natural Linen",
      dimensions: "D300 x H520mm",
      lampHolder: "1x E27 Warm White",
      finish: "Off-White Textured Clay & Oatmeal Linen",
      voltage: "220V"
    }
  },
  {
    id: "prod-KK8038A",
    name: "KK8038A Sculptural Natural Travertine Stone Table Lamp",
    category: "table-floor",
    room: "living",
    price: 6950,
    originalPrice: 9280,
    discount: "25% OFF",
    rating: 5.0,
    reviewsCount: 17,
    image: "assets/products/table-floor.jpg",
    featured: true,
    trending: false,
    inStock: true,
    badge: "Natural Travertine",
    description: "Raw, porous travertine stone block crowned with a brushed brass dome diffuser, representing luxury organic design.",
    specs: {
      modelCode: "KK8038A",
      material: "Raw Natural Italian Travertine Stone & Solid Brass",
      dimensions: "W220 x H450mm",
      lampHolder: "1x E14 Warm LED",
      finish: "Natural Beige Stone & Satin Brass",
      voltage: "220V"
    }
  },
  {
    id: "prod-KK9232A",
    name: "KK9232A Architect Multi-Joint Adjustable Arm Desk Lamp",
    category: "table-floor",
    room: "office",
    price: 3990,
    originalPrice: 5440,
    discount: "27% OFF",
    rating: 4.8,
    reviewsCount: 35,
    image: "assets/products/table-floor.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Architect Desk",
    description: "Precision balanced multi-joint drafting lamp providing directable anti-glare light for home offices and studios.",
    specs: {
      modelCode: "KK9232A",
      material: "Heavy Aluminum Frame & Brass Tension Springs",
      dimensions: "Adjustable Reach H700mm",
      lampHolder: "1x E27 LED",
      finish: "Matte Black & Gold Knobs",
      voltage: "220V"
    }
  },
  {
    id: "prod-DYA17141",
    name: "DYA17141 Classic Banker's Emerald Green Glass Lamp",
    category: "table-floor",
    room: "office",
    price: 2850,
    originalPrice: 3840,
    discount: "26% OFF",
    rating: 4.9,
    reviewsCount: 42,
    image: "assets/products/table-floor.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Vintage Banker",
    description: "Timeless traditional banker's lamp featuring an emerald green glass swivel hood and classic brass pull chain.",
    specs: {
      modelCode: "DYA17141",
      material: "Emerald Green Cased Glass & Cast Brass Base",
      dimensions: "W270 x H380mm",
      lampHolder: "1x E27 Pull Chain Switch",
      finish: "Emerald Green & Antique Brass",
      voltage: "220V"
    }
  },
  {
    id: "prod-KK9279AA",
    name: "KK9279AA Sculptural Arched Floor Lamp with Marble Base",
    category: "table-floor",
    room: "living",
    price: 8400,
    originalPrice: 11200,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 38,
    image: "assets/products/lamp-arched-marble.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Arched Floor Lamp",
    description: "Sweeping architectural floor lamp anchored by a solid black marble pedestal, casting light gracefully over sofas.",
    specs: {
      modelCode: "KK9279AA",
      material: "Brushed Brass Stem & Heavy Black Marquina Marble",
      dimensions: "W450 x H1650mm",
      lampHolder: "1x E27 Warm LED",
      finish: "Brushed Brass & Black Marble",
      voltage: "220V"
    }
  },
  {
    id: "prod-KK9356AA",
    name: "KK9356AA Amber Disc Ambient Luxury Floor Lamp",
    category: "table-floor",
    room: "living",
    price: 12450,
    originalPrice: 16640,
    discount: "25% OFF",
    rating: 5.0,
    reviewsCount: 22,
    image: "assets/products/lamp-arched-marble.jpg",
    featured: true,
    trending: false,
    inStock: true,
    badge: "Amber Disc",
    description: "Large glowing amber disc radiating a sunset glow across high-end living room seating areas.",
    specs: {
      modelCode: "KK9356AA",
      material: "Champagne Amber Acrylic Disc & Brass Pillar",
      dimensions: "Diameter 400mm x Height 1580mm",
      wattageCct: "36W 3-CCT Dimmable LED",
      finish: "Champagne Amber & Gold",
      voltage: "220V"
    }
  },
  {
    id: "prod-KK9089AA",
    name: "KK9089AA Twin Globe Carrara Marble Floor Standing Fixture",
    category: "table-floor",
    room: "living",
    price: 12900,
    originalPrice: 17280,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 19,
    image: "assets/products/lamp-arched-marble.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Carrara Marble",
    description: "Dual illuminated opal glass spheres branching from a gold stem grounded in an authentic white Carrara marble base.",
    specs: {
      modelCode: "KK9089AA",
      material: "Solid White Carrara Marble & Opal Glass Globes",
      dimensions: "W380 x H1600mm",
      lampHolder: "2x G9 Warm LED",
      finish: "White Carrara Marble & Gold",
      voltage: "220V"
    }
  },
  {
    id: "prod-DYC058",
    name: "DYC058 Integrated Walnut Pedestal Table Floor Lamp",
    category: "table-floor",
    room: "bedroom",
    price: 8850,
    originalPrice: 11840,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 26,
    image: "assets/products/table-floor.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "2-in-1 Table Lamp",
    description: "Functional two-in-one floor standing lamp with an integrated circular walnut side table shelf.",
    specs: {
      modelCode: "DYC058",
      material: "Solid Walnut Wood Shelf & Brass Upright",
      dimensions: "Table D400mm x Total H1450mm",
      lampHolder: "1x E27 Bulb",
      finish: "Natural Walnut & Satin Gold",
      voltage: "220V"
    }
  },
  {
    id: "prod-B8107",
    name: "Beluga B8107/3 3-Globe Vertical Pillar Floor Lamp",
    category: "table-floor",
    room: "living",
    price: 8640,
    originalPrice: 11520,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 33,
    image: "assets/products/lamp-arched-marble.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Beluga 3-Globe",
    description: "Vertical totem of three glowing opal globes delivering balanced 360-degree room lighting.",
    specs: {
      modelCode: "BELUGA-B8107/3",
      material: "Opal White Glass & Satin Gold Column",
      dimensions: "W300 x H1500mm",
      lampHolder: "3x G9 Bulbs",
      finish: "Satin French Gold & White Glass",
      voltage: "220V"
    }
  },

  // ================= 6. CEILING & FLUSH LIGHTS =================
  {
    id: "prod-SS1882",
    name: "SS1882 Ultra Slim Geometric Square Flush Ceiling Light",
    category: "ceiling",
    room: "bedroom",
    price: 2350,
    originalPrice: 3160,
    discount: "26% OFF",
    rating: 4.8,
    reviewsCount: 44,
    image: "assets/products/ceiling.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Ultra Slim",
    description: "Ultra-thin 50mm profile ceiling flush light with remote control color temperature and nightlight mode.",
    specs: {
      modelCode: "SS1882",
      material: "Aviation Aluminum & Optical PMMA",
      dimensions: "500 x 500mm x Thickness 50mm",
      wattageCct: "48W 3-CCT Tunable LED",
      finish: "Matte Sand White",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-TN2608A",
    name: "TN2608A Concentric Triple Ring Modern Ceiling Flush Fixture",
    category: "ceiling",
    room: "living",
    price: 8350,
    originalPrice: 11200,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 35,
    image: "assets/products/ceiling-triple-ring.jpg",
    featured: true,
    trending: false,
    inStock: true,
    badge: "Triple Ring",
    description: "Three overlapping luminous gold rings mounted flush to the ceiling, ideal for bedrooms and living rooms.",
    specs: {
      modelCode: "TN2608A",
      material: "Gold Plated Metal & Silica Diffusers",
      dimensions: "D600mm x H100mm",
      wattageCct: "72W High Lumen LED",
      finish: "French Gold & Black",
      voltage: "220V"
    }
  },
  {
    id: "prod-MTB8824",
    name: "MTB8824-6L 6-Way Multi-Directional Modern Ceiling Fixture",
    category: "ceiling",
    room: "living",
    price: 7650,
    originalPrice: 10250,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 28,
    image: "assets/products/ceiling.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "6-Way Semi-Flush",
    description: "Semi-flush 6-arm fixture with low ceiling clearance, delivering widespread ambient illumination.",
    specs: {
      modelCode: "MTB8824-6L",
      material: "Forged Steel & Brass Sockets",
      dimensions: "D750mm x H250mm",
      lampHolder: "6x E27 Bulbs",
      finish: "Matte Black & Brass",
      voltage: "220V"
    }
  },
  {
    id: "prod-LR7229",
    name: "LR7229/5 5-Leaf Flower Blossom Crystal Ceiling Light",
    category: "ceiling",
    room: "living",
    price: 10750,
    originalPrice: 14330,
    discount: "25% OFF",
    rating: 5.0,
    reviewsCount: 32,
    image: "assets/products/ceiling.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Crystal Blossom",
    description: "Artistic floral crystal petals blooming from a gold core with remote-controlled light moods.",
    specs: {
      modelCode: "LR7229/5",
      material: "Faceted K9 Crystal Petals & Gold Chassis",
      dimensions: "D680mm x H120mm",
      wattageCct: "65W 3-CCT LED",
      finish: "Polished Gold & Clear Crystal",
      voltage: "220V"
    }
  },
  {
    id: "prod-JH26001",
    name: "JH26001 Sunburst Surface Mounted Architectural Ceiling Light",
    category: "ceiling",
    room: "bedroom",
    price: 4800,
    originalPrice: 6435,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 21,
    image: "assets/products/ceiling-triple-ring.jpg",
    featured: false,
    trending: false,
    inStock: true,
    badge: "Sunburst",
    description: "Circular surface ceiling fixture with subtle radial halo backlighting on the ceiling surface.",
    specs: {
      modelCode: "JH26001",
      material: "Sand White Frame & Rose Gold Accents",
      dimensions: "D500mm x H65mm",
      wattageCct: "40W LED Tunable",
      finish: "White & Rose Gold",
      voltage: "220V"
    }
  },

  // ================= 7. 48V LOW VOLTAGE MAGNETIC TRACK LIGHTS =================
  {
    id: "prod-GMT-01",
    name: "GMT-01 48V Low Voltage Magnetic Track Rail (2-Meter Surface/Recessed)",
    category: "track",
    room: "office",
    price: 2400,
    originalPrice: 3200,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 46,
    image: "assets/products/track-system.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "48V Safe Rail",
    description: "Heavy-duty 48V DC magnetic profile track supporting plug-and-play repositioning of floodlights, spots, and pendants.",
    specs: {
      modelCode: "GMT-01 (2M)",
      material: "Architectural Extruded 6063 Aluminum",
      dimensions: "2000mm L x 35mm W x 35mm H",
      wattageCct: "48V DC Copper Busbar (Max 200W)",
      finish: "Matte Deep Anodized Black",
      voltage: "48V DC Low Voltage"
    }
  },
  {
    id: "prod-GMT-02",
    name: "GMT-02 Magnetic Linear Flood Diffused Light Module (12W)",
    category: "track",
    room: "office",
    price: 1390,
    originalPrice: 1850,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 38,
    image: "assets/products/track-system.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Linear Diffused",
    description: "Magnetic snap-in diffused linear light module delivering smooth, glare-free ambient line lighting.",
    specs: {
      modelCode: "GMT-02 (12W)",
      material: "Aluminum Body & Frosted Opal Optical Cover",
      dimensions: "L300mm x W22mm Snap-in",
      wattageCct: "12W Osram LED (3000K/4000K, RA>90)",
      finish: "Matte Black",
      voltage: "48V DC"
    }
  },
  {
    id: "prod-GMT-03",
    name: "GMT-03 Magnetic Linear Darklight Grille Module (18W Anti-Glare UGR<16)",
    category: "track",
    room: "office",
    price: 1850,
    originalPrice: 2450,
    discount: "24% OFF",
    rating: 5.0,
    reviewsCount: 52,
    image: "assets/products/track-system.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Anti-Glare UGR<16",
    description: "Deep louvered anti-glare architectural module preventing eye strain while illuminating workspaces and luxury offices.",
    specs: {
      modelCode: "GMT-03 (18W)",
      material: "Deep Micro-Baffles & Optical Black Honeycomb",
      dimensions: "L450mm x W22mm",
      wattageCct: "18W Bridgelux LED, UGR<16",
      finish: "Matte Black Darklight",
      voltage: "48V DC"
    }
  },
  {
    id: "prod-GMT-04",
    name: "GMT-04 Magnetic 360° Rotatable Architectural Spotlight (10W)",
    category: "track",
    room: "living",
    price: 1450,
    originalPrice: 1950,
    discount: "26% OFF",
    rating: 4.9,
    reviewsCount: 41,
    image: "assets/products/track.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "360° Spotlight",
    description: "Fully articulated 360-degree rotating and 90-degree tilting magnetic spotlight for highlighting artwork and focal walls.",
    specs: {
      modelCode: "GMT-04 (10W)",
      material: "CNC Machined Aluminum & 24° Optical Lens",
      dimensions: "D45mm x L120mm",
      wattageCct: "10W CREE COB LED (RA>92)",
      finish: "Matte Black & Gold Ring",
      voltage: "48V DC"
    }
  },
  {
    id: "prod-GMT-05",
    name: "GMT-05 Magnetic Suspension Cylinder Pendant Module (12W)",
    category: "track",
    room: "dining",
    price: 1950,
    originalPrice: 2600,
    discount: "25% OFF",
    rating: 4.8,
    reviewsCount: 29,
    image: "assets/products/track.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Track Pendant",
    description: "Snap-in magnetic hanging cylinder pendant that slides anywhere along the magnetic rail above dining and island tables.",
    specs: {
      modelCode: "GMT-05 (12W)",
      material: "Slender Aluminum Tube & Brass Ring",
      dimensions: "D40mm x L300mm (Drop Cord 1200mm)",
      wattageCct: "12W Warm White 3000K",
      finish: "Matte Black & Gold Collar",
      voltage: "48V DC"
    }
  },
  {
    id: "prod-SMT-01",
    name: "SMT-01 Ultra-Slim In-Track 48V Power Supply Driver (100W)",
    category: "track",
    room: "office",
    price: 2550,
    originalPrice: 3400,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 34,
    image: "assets/products/track-system.jpg",
    featured: false,
    trending: false,
    inStock: true,
    badge: "100W Power Driver",
    description: "Concealed inside-track power supply unit that clips into the magnetic channel without needing an external driver box.",
    specs: {
      modelCode: "SMT-01 (100W)",
      material: "Reinforced Aluminum Shielding Driver",
      dimensions: "In-track concealed module",
      wattageCct: "100W 48V DC Constant Voltage Output",
      finish: "Concealed Black",
      voltage: "Input 220V / Output 48V DC"
    }
  },

  // ================= 8. OUTDOOR & LANDSCAPE LIGHTS =================
  {
    id: "prod-GOL-01",
    name: "GOL-01 Heavy-Duty IP65 Architectural Path Bollard (60cm)",
    category: "outdoor",
    room: "outdoor",
    price: 2100,
    originalPrice: 2800,
    discount: "25% OFF",
    rating: 4.9,
    reviewsCount: 37,
    image: "assets/products/outdoor-bollard.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "IP65 Weatherproof",
    description: "Robust pathway bollard designed to withstand harsh monsoon rains and dust while illuminating garden walkways.",
    specs: {
      modelCode: "GOL-01 (60CM)",
      material: "Anti-Corrosion Die-cast Aluminum & Tempered Glass",
      dimensions: "Height 600mm x Diameter 90mm",
      wattageCct: "10W Sealed Warm White 3000K LED",
      finish: "Anthracite Dark Grey",
      protection: "IP65 Waterproof & Dustproof"
    }
  },
  {
    id: "prod-GOL-02",
    name: "GOL-02 IP67 Waterproof Outdoor Garden Landscape Spike Light (7W)",
    category: "outdoor",
    room: "outdoor",
    price: 1190,
    originalPrice: 1650,
    discount: "28% OFF",
    rating: 4.8,
    reviewsCount: 49,
    image: "assets/products/outdoor.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "IP67 Spike Light",
    description: "Adjustable landscape spike light for uplighting trees, palms, shrubs, and exterior stone facades.",
    specs: {
      modelCode: "GOL-02 (7W)",
      material: "Heavy Aluminum Body & Ground Anchor Stake",
      dimensions: "D60 x L95mm + 160mm Stake",
      wattageCct: "7W CREE COB (30° Beam)",
      finish: "Sand Black",
      protection: "IP67 Submersible Waterproof"
    }
  },
  {
    id: "prod-GOL-03",
    name: "GOL-03 Dual-Beam Narrow Facade Column Projector Light (18W IP66)",
    category: "outdoor",
    room: "outdoor",
    price: 2950,
    originalPrice: 3950,
    discount: "25% OFF",
    rating: 5.0,
    reviewsCount: 26,
    image: "assets/products/wall-up-down.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Facade Beam",
    description: "Powerful pencil-beam facade projector casting tall 10-meter upward and downward architectural pillars of light on bungalow exteriors.",
    specs: {
      modelCode: "GOL-03 (18W)",
      material: "Die-cast Heavy Alloy & 8° Narrow Lenses",
      dimensions: "W120 x H240mm",
      wattageCct: "18W High Power LED (Up & Down Beam)",
      finish: "Dark Grey IP66",
      protection: "IP66 High Pressure Water Resistance"
    }
  },
  {
    id: "prod-GOL-04",
    name: "GOL-04 Solar Smart Motion Sensor Exterior Security Wall Light",
    category: "outdoor",
    room: "outdoor",
    price: 1350,
    originalPrice: 1850,
    discount: "27% OFF",
    rating: 4.7,
    reviewsCount: 33,
    image: "assets/products/outdoor.jpg",
    featured: false,
    trending: false,
    inStock: true,
    badge: "Solar + PIR Sensor",
    description: "Zero-electricity solar exterior wall light with automatic twilight activation and PIR motion detection.",
    specs: {
      modelCode: "GOL-04 Solar",
      material: "UV Resistant Polycarbonate & Monocrystalline Panel",
      dimensions: "W140 x H200mm",
      wattageCct: "8W LED + 2200mAh Lithium Battery",
      finish: "Matte Black",
      protection: "IP65 Weatherproof"
    }
  },
  {
    id: "prod-GBL-01",
    name: "GBL-01 Modern Geometric Recessed Step & Footlight (3W IP65)",
    category: "outdoor",
    room: "outdoor",
    price: 690,
    originalPrice: 950,
    discount: "27% OFF",
    rating: 4.8,
    reviewsCount: 41,
    image: "assets/products/outdoor.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Step Footlight",
    description: "Recessed stair and wall footlight providing downward soft guide lighting for outdoor steps, ramps, and boundary walls.",
    specs: {
      modelCode: "GBL-01 (3W)",
      material: "Die-cast Aluminum Housing & Wall Box",
      dimensions: "85 x 85mm Face, Depth 50mm",
      wattageCct: "3W Warm White 3000K",
      finish: "Dark Grey IP65",
      protection: "IP65 Step Light"
    }
  },

  // ================= 9. SMART TUNABLE & CONNECTED LIGHTS =================
  {
    id: "prod-SMART-01",
    name: "Smart WiFi + Bluetooth RGB & CCT Ambient Controller Bulb (12W)",
    category: "smart",
    room: "bedroom",
    price: 899,
    originalPrice: 1499,
    discount: "40% OFF",
    rating: 4.9,
    reviewsCount: 72,
    image: "assets/products/smart-halo.jpg",
    featured: true,
    trending: true,
    inStock: true,
    badge: "Tuya / Alexa",
    description: "Voice-controlled smart bulb with 16 million RGB colors, music synchronization, and programmable sunrise wakeup schedules.",
    specs: {
      modelCode: "SMART-BULB-12W",
      material: "Thermal Polycarbonate & Aluminum Core",
      dimensions: "Standard B22 / E27",
      wattageCct: "12W (1100 Lumens RGB + Tunable White)",
      connectivity: "WiFi 2.4GHz + BLE Mesh (Alexa/Google Home)",
      voltage: "220-240V"
    }
  },
  {
    id: "prod-SMART-02",
    name: "Smart Multi-Scene Wireless Rotary Dimmer & Scene Switch",
    category: "smart",
    room: "living",
    price: 1850,
    originalPrice: 2600,
    discount: "29% OFF",
    rating: 4.9,
    reviewsCount: 36,
    image: "assets/products/smart.jpg",
    featured: false,
    trending: true,
    inStock: true,
    badge: "Rotary Dimmer",
    description: "Premium tactile rotary knob switch for stepless chandelier dimming and one-touch lighting scene selection.",
    specs: {
      modelCode: "SMART-ROTARY-01",
      material: "Brushed Aluminum Knob & Glass Bezel",
      dimensions: "86 x 86mm Standard Box",
      compatibility: "Zigbee 3.0 / WiFi Gateway",
      control: "Smooth 1-100% Dimming & CCT Control",
      voltage: "220V"
    }
  }
];

export const DEFAULT_INQUIRIES = [
  {
    id: "inq-101",
    customerName: "Rajesh Patel",
    phone: "+91 98251 44321",
    roomType: "Living Room Duplex",
    interest: "MTD23775-7D Grand Duplex Spiral Chandelier",
    preferredDate: "Tomorrow, 4:00 PM",
    notes: "Needs consultation for high ceiling bungalow in Infocity Gandhinagar.",
    status: "New",
    dateSubmitted: "2026-09-08 11:30 AM"
  },
  {
    id: "inq-102",
    customerName: "Dr. Meera Shah",
    phone: "+91 94280 88712",
    roomType: "Modern Clinic / Office",
    interest: "GMT-01 48V Magnetic Track Light System",
    preferredDate: "Weekend 11:00 AM",
    notes: "Requires anti-glare UGR<16 lighting for new consultation room in Kudasan.",
    status: "Showroom Scheduled",
    dateSubmitted: "2026-09-07 05:15 PM"
  }
];

export const DEFAULT_SLIDERS = [
  {
    id: "slide-1",
    title: "Grand Festive & Inaugural Offer",
    highlightText: "Upto 35% OFF",
    subtitle: "Experience luxury crystal chandeliers, designer pendants, and smart lighting with exclusive showroom discounts.",
    badge: "Special Showroom Offer 🔥",
    image: "assets/hero.jpg",
    btnText: "Claim Offer & Shop Now",
    btnLink: "#productsSection",
    secondaryBtnText: "Book Consultation",
    secondaryBtnLink: "modal:consultation",
    order: 1,
    active: true
  },
  {
    id: "slide-2",
    title: "Architectural Designer Wall Lights",
    highlightText: "Dual Beam & Warm Ambience",
    subtitle: "Transform plain walls into sculptural statements with modern waterproof sconces and warm amber cones.",
    badge: "Wall Light Collection ✨",
    image: "assets/products/wall-up-down.jpg",
    btnText: "Explore Wall Lights",
    btnLink: "#productsSection",
    secondaryBtnText: "See In Room",
    secondaryBtnLink: "modal:visualizer",
    order: 2,
    active: true
  },
  {
    id: "slide-3",
    title: "Royal K9 Faceted Crystal Chandeliers",
    highlightText: "Timeless Grandeur",
    subtitle: "Breathtaking double-height chandeliers handcrafted for high-ceiling living rooms, bungalows, and duplexes.",
    badge: "Showroom Bestseller 💎",
    image: "assets/products/chandelier-imperial-crown.jpg",
    btnText: "View Grand Chandeliers",
    btnLink: "#productsSection",
    secondaryBtnText: "WhatsApp Inquiry",
    secondaryBtnLink: "https://wa.me/919898091234?text=Hello%20JK%20Lights!%20I%20am%20interested%20in%20the%20Royal%20Crystal%20Chandelier.",
    order: 3,
    active: true
  },
  {
    id: "slide-4",
    title: "Modern Pendants & Architectural Tracks",
    highlightText: "Contemporary Living",
    subtitle: "Sleek dining pendants, anti-glare magnetic tracks, and 3-color tunable ceiling lights engineered for elegance.",
    badge: "Trending 2026 🌟",
    image: "assets/products/track-system.jpg",
    btnText: "Discover Pendants",
    btnLink: "#productsSection",
    secondaryBtnText: "Visit Showroom",
    secondaryBtnLink: "#showroomSection",
    order: 4,
    active: true
  }
];

export const DEFAULT_BLOGS = [
  {
    id: "blog-1",
    title: "How to Choose the Perfect Chandelier Size for Your Living Room",
    category: "Design Guide",
    date: "Sep 2026",
    readTime: "4 min read",
    image: "assets/products/chandelier-imperial-crown.jpg",
    summary: "Discover the golden rule of room dimensions (Length + Width in feet = Chandelier diameter in inches) and ceiling height clearance tips for grand homes.",
    author: "JK Design Studio",
    content: `When selecting a luxury chandelier for your living room or duplex foyer, proportions are everything. A chandelier that is too small gets lost in the space, while an oversized fixture can overwhelm your interior architecture.

Here is the golden mathematical formula used by lighting architects across Gujarat:
1. Measure your room's Length and Width in feet (e.g., 20 feet by 16 feet).
2. Add these two numbers together: 20 + 16 = 36.
3. Convert that sum to inches: Your ideal chandelier diameter is approximately 36 inches (900mm to 1000mm).

For ceiling height clearance, always maintain at least 7 to 8 feet of clearance from the bottom of the chandelier to the floor in walking zones. In double-height living spaces (18-22 feet), opt for vertical cascading spiral crystal designs with drops of 10 to 16 feet.`,
    proTip: "In duplex stairwells or double-height foyers, choose a chandelier with motorized suspension lifters to make crystal cleaning and bulb maintenance effortless!",
    featured: true,
    tags: ["Chandeliers", "Duplex", "Calculations", "Living Room"]
  },
  {
    id: "blog-2",
    title: "Warm (2700K) vs Neutral (4000K) vs Cool (6500K): Which is Right?",
    category: "Lighting 101",
    date: "Aug 2026",
    readTime: "5 min read",
    image: "assets/products/wall-marble.jpg",
    summary: "Understand color temperatures to create cozy bedrooms, productive home offices, and sparkling dining areas without harsh glare.",
    author: "Architectural Lighting Team",
    content: `Light color temperature (measured in Kelvin) dictates the emotional atmosphere and biological comfort of your residence.

Here is how to select the right color temperature for each zone:
• 2700K - 3000K (Warm White): Produces an amber, candle-like glow that triggers relaxation. Perfect for master bedrooms, luxury living room chandeliers, bedside wall sconces, and dining areas.
• 4000K (Natural / Neutral White): Clean, crisp, and true-to-life without yellow or blue tints. Essential for modern kitchens, vanity mirrors, wardrobe dressing zones, and study tables.
• 5000K - 6500K (Cool Daylight): High alertness light best suited for commercial spaces, utility laundry zones, and exterior landscape security floodlights.

At JK Lights Gandhinagar, we recommend installing 3-CCT Smart Tunable fixtures so you can transition smoothly from 4000K focus during daytime to 2700K cozy ambiance at dusk.`,
    proTip: "Never mix 2700K and 6500K light sources in the same direct line of sight. It causes visual fatigue and makes luxury woodwork appear distorted.",
    featured: true,
    tags: ["Kelvin", "Warm White", "CCT", "Interior Design"]
  },
  {
    id: "blog-3",
    title: "Why Magnetic Track Lighting is the Top Choice for Modern Villas in 2026",
    category: "Trends 2026",
    date: "Aug 2026",
    readTime: "3 min read",
    image: "assets/products/track-system.jpg",
    summary: "Discover the flexibility of 48V low-voltage magnetic rails allowing you to reposition spot, flood, and pendant lights effortlessly without rewiring.",
    author: "JK Lights Gandhinagar",
    content: `Traditional fixed ceiling spotlights are quickly being replaced by 48V Low-Voltage Magnetic Architectural Track Systems in new villas and bungalows across Gandhinagar and Ahmedabad.

Key benefits of magnetic track systems:
1. Tool-Free Repositioning: Simply snap spotlights, linear diffusers, wall washers, or mini hanging drops in and out with magnetic lock clicks.
2. Ultra-Safe 48V DC Low Voltage: Completely touch-safe with zero risk of electric shock during adjustments.
3. Minimalist Trimless Architecture: Recessed seamlessly into false ceilings for razor-sharp, modern visual lines.
4. Anti-Glare Dark Light Grilles: Deep recessed optics (UGR < 16) provide brilliant floor lux levels while concealing the raw LED glare from eye level.`,
    proTip: "Plan your magnetic track layout before false ceiling plastering. Recessed tracks require early channel framing with your POP contractor.",
    featured: false,
    tags: ["Magnetic Tracks", "Architectural", "Modern Villa", "Anti-Glare"]
  }
];

export const DEFAULT_FAQS = [
  {
    id: "faq-1",
    question: "Do you provide on-site lighting consultation in Gandhinagar and Ahmedabad?",
    answer: "Yes! Our specialized architectural lighting consultants offer free on-site visits across Gandhinagar (Kudasan, Infocity, Raysan, PDPU road) and Ahmedabad. We evaluate your floor plans, ceiling heights, and color schemes to recommend ideal lumen levels and fixture placements."
  },
  {
    id: "faq-2",
    question: "Can I customize the size, finish, and crystal quality of chandeliers?",
    answer: "Absolutely. We specialize in custom-built crystal and brass chandeliers tailored specifically for duplexes, banquet halls, and double-height staircases with custom drops up to 20+ feet."
  },
  {
    id: "faq-3",
    question: "What warranty and after-sales support do you offer?",
    answer: "All our designer lighting fixtures and LED drivers come with a minimum 1-year comprehensive showroom warranty. We also maintain spare crystals, drivers, and LED chips in our Kudasan showroom."
  },
  {
    id: "faq-4",
    question: "Do you offer professional installation and delivery?",
    answer: "Yes, our certified electrician team handles safe transportation, heavy-duty ceiling anchoring, crystal assembly, and electrical testing across Gujarat."
  },
  {
    id: "faq-5",
    question: "Where is the JK Lights showroom located in Gandhinagar?",
    answer: "Our flagship showroom is located on the 2nd Floor, VTC Complex (Vrundavan Trade Center), Above Kabir World, Reliance Cross Road, Kudasan, Gandhinagar - 382421. Open Mon-Sat 10:00 AM - 9:30 PM & Sunday 11:00 AM - 8:00 PM."
  }
];
